# This program accesses the Twitter API to get Tweets for a hashtag
# Takes as input - Hashtag and How long to stream Tweets
# Output - Top N Words for a given hashtag for a given time

#Replace consumerAPIKey, consumerSecretKey, accessToken, accessTokenSecret with valid values 

import json
import time
import collections
from tweepy import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream


class StdOutListener(StreamListener):
    def __init__(self, start_time, time_limit=60):
        self.time = start_time
        self.limit = time_limit
        self.list_of_words = []
        self.top_hundred = {}

    def on_data(self, data):
        if (time.time() - self.time) < self.limit:
            all_data = json.loads(data)  # This is the whole response from twitter
            text = all_data.get('text')  # Taking only the text part of interest to us for counting
            split_strings = text.split()   # The string is split
            for word in split_strings:                # Updating a Dictionary directly would have been a better choice
                self.list_of_words.append(word)   # The split words are appended to a list
            return True
        else:
            self.computations()
            return False

    def computations(self):
        # print(list_of_words)
        final_count = collections.Counter(self.list_of_words)  # now count the list to get the words
        self.top_hundred = final_count.most_common(100)    # Top hundred words
        # json_format = json.dumps(self.top_hundred)
        return self.top_hundred

    def on_error(self, status):
        print(status)


class SetupTweetCollector:
    def __init__(self, keyword, duration):
        hashtag = '#' + keyword
        # Keys generated by creating an app on the Twitter website
        # Credentials required to access the Twitter API
        consumerAPIKey = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        consumerSecretKey = 'yyyyyyyyyyyyyyyyyyyyyyyyyyy'
        # Access tokens
        accessToken = 'zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz'
        accessTokenSecret = 'xxxxxxxxxxyyyyyyyyyyyzzzzzzzzzzaaaa'

        # This handles Twitter authentication and the connection to Twitter Streaming API
        start_time = time.time()
        self.listener = StdOutListener(start_time, duration)
        auth = OAuthHandler(consumerAPIKey, consumerSecretKey)
        auth.set_access_token(accessToken, accessTokenSecret)

        stream = Stream(auth, self.listener)

        # This line filters Twitter Streams to capture data by the keywords
        stream.filter(track=[hashtag])

    def retrieve(self):
        return self.listener.top_hundred



